# Generated by Django 2.2.4 on 2019-10-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191008_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
