# Generated by Django 2.2.4 on 2019-10-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191008_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='cahce_hit',
            field=models.BooleanField(default=False),
        ),
    ]
