# Generated by Django 2.2.4 on 2019-10-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_myuser_cahce_hit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='cahce_hit',
            new_name='cache_hit',
        ),
    ]
