# Generated by Django 2.2.4 on 2019-10-08 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191008_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_profile_data',
            old_name='verified',
            new_name='cache_hit',
        ),
        migrations.RenameField(
            model_name='creator_profile_data',
            old_name='verified',
            new_name='cache_hit',
        ),
    ]
