# Generated by Django 2.2.4 on 2019-10-08 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191008_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirtybit', models.UUIDField(blank=True, null=True, unique=True)),
                ('connection_dirtybit', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=1000)),
                ('extra_data', models.TextField(blank=True, max_length=10000, null=True)),
                ('access_expiry', models.DateTimeField(blank=True, null=True)),
                ('long_token', models.CharField(max_length=1000)),
                ('long_expiry', models.DateTimeField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
