# Generated by Django 2.2.4 on 2019-10-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='long_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
