# Generated by Django 2.2.4 on 2019-10-08 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_available_package_current_package_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirtybit', models.UUIDField(blank=True, null=True, unique=True)),
                ('schedule_dirtybit', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('content', models.TextField(blank=True, max_length=63000, null=True)),
                ('datetime', models.DateTimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.connections')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
