# Generated by Django 2.2.4 on 2019-10-09 10:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_scheduler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='datetime',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='image',
            field=models.ImageField(blank=True, upload_to='scheduled_images'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='scheduled_datetime',
            field=models.DateTimeField(default='1996-12-26 16:10:06'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='upload_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='video',
            field=models.FileField(blank=True, upload_to='scheduled_videos'),
        ),
        migrations.CreateModel(
            name='init_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirtybit', models.UUIDField(blank=True, null=True, unique=True)),
                ('providers', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, max_length=63000, null=True)),
                ('scheduled_datetime', models.DateTimeField(default='1996-12-26 16:10:06')),
                ('upload_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, upload_to='scheduled_images')),
                ('video', models.FileField(blank=True, upload_to='scheduled_videos')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scheduler',
            name='init_schedule_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.init_schedule'),
        ),
    ]
