# Generated by Django 2.2.4 on 2019-10-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191009_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='init_schedule',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='scheduled_datetime',
            field=models.DateTimeField(),
        ),
    ]
