# Generated by Django 2.2.4 on 2019-10-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_connections_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='account_uid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
