# Generated by Django 2.2.4 on 2019-10-09 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20191009_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='init_schedule',
            name='self_dirtybit',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='init_schedule',
            name='dirtybit',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
