# Generated by Django 2.2.4 on 2019-10-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20191009_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='dirtybit',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
