# Generated by Django 2.2.4 on 2019-10-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20191009_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='scheduler',
            new_name='scheduler_model',
        ),
    ]
