# Generated by Django 2.2.4 on 2019-10-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20191009_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler_model',
            name='timestamp',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
