# Generated by Django 2.2.4 on 2019-10-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_scheduler_model_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler_model',
            name='timestamp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
