# Generated by Django 2.2.4 on 2019-10-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20191012_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler_model',
            name='hit',
            field=models.BooleanField(default=False),
        ),
    ]
