# Generated by Django 2.2.4 on 2019-10-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20191012_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomming_queue',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.connections'),
        ),
    ]
