# Generated by Django 2.2.4 on 2019-10-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_upcomming_queue_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler_model',
            name='timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upcomming_queue',
            name='timestamp',
            field=models.BigIntegerField(blank=True, max_length=20, null=True),
        ),
    ]
