# Generated by Django 2.2.4 on 2019-10-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20191016_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='connections',
            new_name='selected_connections',
        ),
    ]
