# Generated by Django 2.2.4 on 2019-10-17 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20191017_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_connection_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirtybit', models.UUIDField(blank=True, null=True)),
                ('max_connections', models.IntegerField(default=0)),
                ('total_connections', models.IntegerField(default=0)),
                ('max_seleceted_connections', models.IntegerField(default=0)),
                ('total_seleceted_connections', models.IntegerField(default=0)),
                ('max_team_members', models.IntegerField(default=0)),
                ('total_team_members', models.IntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='queue_statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirtybit', models.UUIDField(blank=True, null=True)),
                ('limit', models.IntegerField(default=10)),
                ('left', models.IntegerField(default=10)),
                ('selected_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.selected_connections')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
