# Generated by Django 2.2.4 on 2019-10-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20191017_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue_statistics',
            name='dirtybit',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
