# Generated by Django 2.2.4 on 2019-10-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_selected_connections_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='selected_connections',
            name='access_token_secret',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
