# Generated by Django 2.2.4 on 2019-10-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_selected_connections_access_token_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue_statistics',
            name='account_uid',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
