# Generated by Django 2.2.4 on 2019-10-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_queue_statistics_account_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected_connections',
            name='access_token',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='selected_connections',
            name='access_token_secret',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='selected_connections',
            name='account_token',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
