# Generated by Django 2.2.4 on 2019-10-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20191018_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rand_save_string', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('accs', models.CharField(blank=True, max_length=1000, null=True)),
                ('cont', models.CharField(blank=True, max_length=50000, null=True)),
                ('img', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
