# Generated by Django 2.2.4 on 2019-10-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20191019_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_data',
            name='date',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
