# Generated by Django 2.2.4 on 2019-11-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_temp_data_uid_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_data',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media_uploaded/'),
        ),
    ]
