# Generated by Django 2.2.4 on 2019-11-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20191115_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler_model',
            name='image',
            field=models.ImageField(blank=True, upload_to='media_uploaded/'),
        ),
    ]
