# Generated by Django 2.2.4 on 2019-11-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20191119_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler_model',
            name='calc',
            field=models.BooleanField(default=False),
        ),
    ]
