# Generated by Django 2.2.4 on 2019-11-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_scheduler_model_calc'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue_statistics',
            name='account_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
