# Generated by Django 2.2.4 on 2019-11-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_queue_statistics_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue_statistics',
            name='provider',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
