# Generated by Django 2.2.4 on 2019-11-20 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_available_package_package_id_int'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_transaction_id', models.UUIDField(default=uuid.uuid4, null=True, unique=True)),
                ('transaction_start', models.DateTimeField()),
                ('current_package', models.CharField(max_length=100, null=True)),
                ('upgrade_package', models.CharField(max_length=100, null=True)),
                ('from_date', models.BigIntegerField()),
                ('to_date', models.BigIntegerField()),
                ('razorpay_payment_url', models.URLField(blank=True, default='https://creatosaurus.in/nopay', max_length=2000)),
                ('razorpay_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
