# Generated by Django 2.2.4 on 2019-11-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_user_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_transaction',
            name='amount',
            field=models.BigIntegerField(default=99900),
        ),
        migrations.AddField(
            model_name='user_transaction',
            name='customer_id',
            field=models.CharField(blank=True, default='NA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_transaction',
            name='order_id',
            field=models.CharField(blank=True, default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_transaction',
            name='razorpay_id',
            field=models.CharField(blank=True, default='NA', max_length=255, null=True),
        ),
    ]
