# Generated by Django 2.2.4 on 2019-11-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20191120_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_transaction',
            name='razorpay_payment_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
