# Generated by Django 2.2.4 on 2019-11-21 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_auto_20191120_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_transaction',
            name='inv_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_transaction',
            name='transaction_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
