# Generated by Django 2.2.4 on 2019-11-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_auto_20191121_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='selected_connections',
            name='within_limit',
            field=models.BooleanField(default=True),
        ),
    ]
