# Generated by Django 2.2.4 on 2019-11-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_selected_connections_within_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_package_user',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
