# Generated by Django 2.2.4 on 2019-11-23 18:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_current_package_user_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_pannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('read_hit', models.BooleanField(default=False)),
                ('mark_as_read_hit', models.BooleanField(default=False)),
                ('read_hit_time', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(max_length=256)),
                ('follow_link', models.URLField(blank=True, null=True)),
                ('u_code', models.IntegerField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
