# Generated by Django 2.2.4 on 2019-11-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_notification_pannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_pannel',
            name='message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
