# Generated by Django 2.2.4 on 2019-11-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_auto_20191123_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='new_user_notify',
            field=models.BooleanField(default=False),
        ),
    ]
