# Generated by Django 2.2.4 on 2019-11-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_myuser_new_user_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_package_user',
            name='package_exipry',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
