# Generated by Django 2.2.4 on 2019-11-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_current_package_user_package_exipry'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_package_user',
            name='last_package',
            field=models.CharField(default='L1', max_length=10),
        ),
    ]
